name: hello world 1

on:
  workflow_dispatch:

jobs:
  hello-1:
    name: echo hello world 1
    uses: ./.github/module/reusable-hello.yml
    with:
      name: Marko Matrovic
      tag: v1.0.0
      version: 23
    secrets:
      token: ${{secrets.GITHUB_TOKEN}}