name: reusable hello

on:
  # this defines that workflow is callable from other workflow
  workflow_call:
    # these are inputs to be provided to workflow
    inputs:
      name:
        required: true
        type: string
      tag:
        required: false
        type: string
      version:
        required: false
        type: number
    secrets:
      # you cannot use github_token it's reserved
      token:
        required: true

jobs:
  say-hello:
    name: say hello
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        # https://github.com/actions/checkout
        uses: actions/checkout@v3
        with:
          # checkout complete history
          fetch-depth: 0

      - name: say hello to name
        run: |
          echo hello ${{inputs.name}}

      - name: contruct image tag
        run: |
          if [ -z "${{inputs.tag}}" ]
          then
            echo "image_tag=latest" >> $GITHUB_ENV
          else
            echo "image_tag=${{inputs.tag}}" >> $GITHUB_ENV
          fi

      - name: echo image_tag from previous step
        run: |
          echo image_tag=${{env.image_tag}}

      - name: echo version
        run: |
          echo version=${{inputs.version}}

      - name: echo token
        run: |
          echo token=${{secrets.token}}
